apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iracluster-conf-files-pvc
spec:
  storageClassName: ""  # <----- Must be empty to match static PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
