apiVersion: v1
kind: PersistentVolume
metadata:
  name: iracluster-conf-files-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if you want it to be writable
  hostPath:
    path: /usr/local/epi/conf
