apiVersion: apps/v1
kind: Deployment
metadata:
  name: irapodtracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irapodtracker
  template:
    metadata:
      labels:
        app: irapodtracker
    spec:
      containers:
        - name: irapodtracker
          image: kaushik699/irapodtracker:8
          volumeMounts:
            - name: conf-volume
              mountPath: /usr/local/epi/conf
      volumes:
        - name: conf-volume
          persistentVolumeClaim:
            claimName: iracluster-conf-files-pvc
