apiVersion: apps/v1
kind: Deployment
metadata:
  name: irapass-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irapass
  template:
    metadata:
      labels:
        app: irapass
    spec:
      containers:
        - name: irapass
          image: kaushik699/irapass:6
          volumeMounts:
            - name: conf-volume
              mountPath: /usr/local/epi/conf
      volumes:
        - name: conf-volume
          persistentVolumeClaim:
            claimName: iracluster-conf-files-pvc
